name: AppleCustomTrees
version: 1.0
api-version: 1.15
author: Apple
main: apple.trees.TreeMain
description: Rewards players that build with points
commands:
  tree_create:
    description: creates a tre
